<script setup>
const d = {
  isContainer: true,
  displayName: "页面",
  widgetList: [
    {
      isContainer: false,
      displayName: "数据表格",
      widgetList: [
        {
          isContainer: false,
          displayName: "按钮",
          props: {
            size: "default",
            type: "primary",
            isPlain: false,
            isText: false,
            isTextBgColor: false,
            isLink: false,
            isRound: false,
            isCircle: false,
            isLoading: false,
            disabled: false,
            hide: false,
            hasLabel: false,
            remark: "",
            label: "按钮",
            icon: "",
            align: "left",
            onCreated: null,
            onMounted: null,
            isTableItem: true,
            onItemClick:
              'console.log(app.getMethodById("datatable_1975512").getSearchParams());',
          },
          type: "button",
          id: "button_68181564",
          tableItemType: "button",
          compType: 0,
          _X_ROW_KEY: "row_575",
        },
        {
          isContainer: false,
          displayName: "按钮",
          props: {
            size: "default",
            type: "primary",
            isPlain: false,
            isText: false,
            isTextBgColor: false,
            isLink: false,
            isRound: false,
            isCircle: false,
            isLoading: false,
            disabled: false,
            hide: false,
            hasLabel: false,
            remark: "",
            label: "按钮",
            icon: "",
            align: "left",
            onCreated: null,
            onMounted: null,
            isTableItem: true,
            onItemClick: null,
          },
          type: "button",
          id: "button_69714577",
          tableItemType: "button",
          compType: 0,
          _X_ROW_KEY: "row_581",
        },
        {
          isContainer: false,
          displayName: "按钮",
          props: {
            size: "default",
            type: "primary",
            isPlain: false,
            isText: false,
            isTextBgColor: false,
            isLink: false,
            isRound: false,
            isCircle: false,
            isLoading: false,
            disabled: false,
            hide: false,
            hasLabel: false,
            remark: "",
            label: "按钮",
            icon: "",
            align: "left",
            onCreated: null,
            onMounted: null,
            isTableItem: true,
            onItemClick: null,
          },
          type: "button",
          id: "button_69881583",
          tableItemType: "button",
          compType: 0,
          _X_ROW_KEY: "row_587",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "赋值",
            value: null,
            zdname: "a",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle:
              "// console.log(app.setValue);\n// return\napp.setValue('input_2252833', '测试点击')",
            isTableItem: true,
          },
          type: "input",
          id: "input_2252833",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_49",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "",
            value: null,
            zdname: "b",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle: null,
            isTableItem: true,
          },
          type: "input",
          id: "input_2269550",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_58",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "",
            value: null,
            zdname: "c",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle: null,
            isTableItem: true,
          },
          type: "input",
          id: "input_2286159",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_67",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "",
            value: null,
            zdname: "d",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle: null,
            isTableItem: true,
          },
          type: "input",
          id: "input_68883305",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_313",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "",
            value: null,
            zdname: "f",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle: null,
            isTableItem: true,
          },
          type: "input",
          id: "input_75551351",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_359",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "",
            value: null,
            zdname: "g",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle: null,
            isTableItem: true,
          },
          type: "input",
          id: "input_75753360",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_368",
        },
        {
          isContainer: false,
          displayName: "输入框",
          props: {
            hasLabel: true,
            size: "default",
            remark: "",
            required: false,
            readonly: false,
            disabled: false,
            isDetail: false,
            hide: false,
            placeholder: "请输入",
            prependText: "",
            appendText: "",
            value: "aaa",
            zdname: "h",
            label: "输入框",
            labelWidth: "120px",
            width: 6,
            type: "text",
            isTrim: false,
            maxlength: null,
            showLimit: false,
            onCreated: null,
            onMounted: null,
            onInput: null,
            onChange: null,
            onFocus: null,
            onBlur: null,
            onHandle: null,
            isTableItem: true,
          },
          type: "input",
          id: "input_75934369",
          tableItemType: "input",
          compType: 1,
          _X_ROW_KEY: "row_377",
        },
        {
          isContainer: false,
          displayName: "下拉框",
          props: {
            hasLabel: true,
            size: "default",
            label: "下拉框",
            required: false,
            disabled: false,
            hide: false,
            placeholder: "请选择",
            remark: "",
            value: "3",
            zdname: "i",
            isDetail: false,
            labelWidth: "120px",
            clearable: true,
            width: 6,
            apiSet: {
              method: "post",
              apiurl: "",
              params: [],
              headers: [],
              contentType: "JSON",
              paramsFormat: "",
              headersFormat: "",
              successFormat: "",
              errorFormat: "",
            },
            list: [
              {
                label: "选项1",
                value: "1",
              },
              {
                label: "选项2",
                value: "2",
              },
              {
                label: "选项3",
                value: "3",
              },
            ],
            onCreated: null,
            onMounted: null,
            onChange: null,
            isTableItem: true,
          },
          type: "select",
          id: "select_7332129",
          tableItemType: "select",
          compType: 1,
          _X_ROW_KEY: "row_134",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "CustomerType",
            remark: "",
            label: "CustomerType",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_2421868",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_78",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "Delivery3",
            remark: "",
            label: "Delivery3",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_93165237",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_239",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "ItemName",
            remark: "",
            label: "ItemName",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_93349240",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_242",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "NativeName",
            remark: "",
            label: "NativeName",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_93529243",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_245",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "OrderDate",
            remark: "",
            label: "OrderDate",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_95602489",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_491",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "OrderId",
            remark: "",
            label: "OrderId",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_1429492",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_494",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "PlateType",
            remark: "",
            label: "PlateType",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_1725495",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_497",
        },
        {
          isContainer: false,
          displayName: "数据表格表头",
          widgetList: [],
          props: {
            hasLabel: false,
            zdname: "TotalCube",
            remark: "",
            label: "TotalCube",
            tableitemWidth: null,
            onFormat: null,
            hide: false,
            isTableItem: true,
            tableItemWidth: null,
          },
          type: "datatableitem",
          id: "datatableitem_13009501",
          tableItemType: "datatableitem",
          compType: 2,
          _X_ROW_KEY: "row_503",
        },
      ],
      props: {
        zdname: null,
        hasLabel: false,
        isDetail: false,
        width: 24,
        height: "100%",
        hide: false,
        apiSet: {
          method: "post",
          apiurl: "/OrderStage/QueryOrder2",
          params: [],
          headers: [],
          contentType: "JSON",
          paramsFormat: "",
          headersFormat: "",
          successFormat: "return res['Data']",
          errorFormat: "",
        },
        size: "small",
        oprateWidth: null,
        rows: "ListOrders",
        count: "OrderCount",
        page: "pageIndex",
        limit: "pageSize",
        pageDefault: 50,
        align: "center",
        singleselect: true,
        hasPage: true,
        initLoadData: true,
        showOverFlow: true,
        isStripe: true,
        isHideChoose: true,
        hideHandleBtn: false,
        treeMode: false,
        treeRowField: "id",
        treeParentField: "pid",
        treeChildrenField: "children",
        treeTransform: false,
        treeExpandAll: false,
        treeAccordion: false,
        isLine: false,
        onCreated: "",
        onMounted: null,
        onDataLoad: null,
      },
      type: "datatable",
      id: "datatable_1975512",
      hidePanel: false,
    },
  ],
  type: "homepage",
  id: "homepage",
  chosenId: "homepage",
  props: {
    label: "",
    width: 24,
    remark: "",
    hide: false,
    onCreated: null,
    onMounted: null,
    height: "100%",
  },
};
</script>

<template>
  <designer></designer>
  <!-- <sunForm :widgetConfig="d"></sunForm> -->
</template>
